name: Build/CI

on: [push, pull_request]

jobs:
  static-analysis:
    name: ğŸ“Š Static Analysis
    uses: ./.github/workflows/static_analysis.yml

  linux-build:
    name: ğŸ§ Linux
    needs: static-analysis
    uses: ./.github/workflows/linux_builds.yml

  windows-build:
    name: ğŸ’» Windows
    needs: static-analysis
    uses: ./.github/workflows/windows_builds.yml